<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>85f0eb1e-d808-45da-8faf-09497bb8df4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2e99af8-b56d-40fe-bc6e-8ced58d262bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ffd8ff4d-9110-493e-92d9-2f9787ede221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>b0590246-62f1-4233-bb63-4c5934138167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d67ab9aa-20ca-4df3-bf23-ee68d38b5ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c5a3db861 ca6235d8b c9cad9086 cfb13c923 cb02b03dd</value>
      <webElementGuid>8197f50e-d86f-44d9-a65b-175e263f901b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-button-primary</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c45a68e-e5f3-4789-ad5d-1a542f7bce4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>b5709f7f-bf09-444b-8555-86a6d626fea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;ced20f163 c413b4aa2&quot;]/main[@class=&quot;c143bcc16 login&quot;]/section[@class=&quot;c407b05e5 _prompt-box-outer&quot;]/div[@class=&quot;c570cf029 c5c98936d&quot;]/div[@class=&quot;ce12fde9f&quot;]/div[@class=&quot;c1ed5cc6e c687674bd&quot;]/form[@class=&quot;cae3faed8 c4540f198&quot;]/div[@class=&quot;ca1220cdf&quot;]/button[@class=&quot;c5a3db861 ca6235d8b c9cad9086 cfb13c923 cb02b03dd&quot;]</value>
      <webElementGuid>ccc3cac1-12a6-4a80-b3ea-c5571a5efb80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='action']</value>
      <webElementGuid>7270175b-e5d7-4c5b-9cbc-54ed73438ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::button[1]</value>
      <webElementGuid>38cae97e-2212-4909-bcb4-da9f0054c2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide password'])[2]/following::button[1]</value>
      <webElementGuid>93d5040e-1eb0-42e5-940b-209a39d2a347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>9c3ff7e0-b026-4822-a344-92140975cf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>0e08843c-87a6-4b84-aab9-ed68e149a022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>567d61bb-ecd5-4e3c-b611-992bdd6039d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
